### PR TITLE
Add xo for linting.

### PR DESCRIPTION
**Pull request by XhmikosR**
@rakeshpai: before merging this, how do you feel about switching to single quotes and ES6?

### CODE REVIEW

**Comment by rakeshpai** [comment]
I don't mind moving to single-quotes and spaces for indentation. We could also switch to ES6, but that'll need a major version bump, since it'll be backwards-incompatible. But that's fine - I'm ok with it.

We could even go the whole way, and use const and arrow functions and other ES6 goodies, if you like.

One little thing: While I'm currently using this module in production, I'm moving away from it soon. (There's nothing wrong with this module - I'm just moving to a fully static site, so this module doesn't fit in anymore.) So, if this module is useful to you, I'd be happy if you could take up stewardship of the project. Let me know if you need my help for anything.

I just feel responsible for the stuff published on npm, so I don't want to break anything for existing users. Within the scope of that, feel free to make changes as you please.

**Comment by XhmikosR** [comment]
Yeah, I'm with you regarding stability.

But as far as I can tell, we can use the ES6 features you mention just fine since tests pass on node.js 4.

**Comment by rakeshpai** [comment]
If the tests pass, all is well. :)

(I had written this module in the node 0.4 or 0.6 days, which predates ES6, and I'm unsure when specific ES6 features landed in node. Supporting 4+ is sufficient though.)

**Comment by rakeshpai** [comment]
Let me know whenever you need me to make a release on npm. I'm guessing this patch requires a major release?

**Comment by XhmikosR** [comment]
Should I change the checksum length to 7 without adding an option, since we are going to bump the major version?

**Comment by rakeshpai** [comment]
Sure! Go for it.

**Comment by XhmikosR** [comment]
@rakeshpai: you can add me on npm if you want (username `xhmikosr`) or publish v.1.0.0 yourself.

Not sure if I'll have the time to make more changes, but I plan to switch to staticify for BootstrapCDN, so I'll use it eventually :)

**Comment by rakeshpai** [comment]
I've added you as a owner of this package on npm.

Just before you publish, could you please double-check the badges in the readme? Maybe it's just my connection, but I couldn't get any of them to load - they all simply timeout for me.

**Comment by XhmikosR** [comment]
I think shields.io has some issues currently that is why the badges don't show up.

**Pull request merged**
