### PR TITLE
Refactoring

### LINKED ISSUE #7: Document options

### LINKED ISSUE #8: Add a `short`  option
Which would return a hash with 7 characters instead of the full md5 checksum.

### LINKED ISSUE #11: Ignore known directories by default
Should speed things up. We could use https://www.npmjs.com/package/ignore-by-default

### LINKED ISSUE #12: Express.js options not being passed to middleware
So, it seems that currently only these are being passed to `send`:

```js
maxage: filePath === req.url ? 0 : MAX_AGE,
index: options.index || 'index.html',
ignore: options.hidden,
```

Now, I wonder, can't we inherit the options from static-serve or something?

Supporting individually our own options seems cumbersome and a lot of duplication.

### PR DESCRIPTION
**Pull request by XhmikosR**
@rakeshpai: here's my latest attempt. The problem *I think* it's deep merging or something. Have a look and see if you can come up with a solution

Fixes #12 , fixes #11, fixes #8, fixes #7.

### CODE REVIEW

**Comment by rakeshpai** [comment]
Not sure what I'm looking at. Could you please explain further?

Also, looks like my changes haven't been merged in?

**Comment by XhmikosR** [comment]
Whatever you had pushed is there, just squashed.

With this refactoring,

1. options are shared
2. the hash is only `slice`d once in `buildVersionHash`
3. I added a new option to ignore known directories, true by default
4. I moved send'`s options to `sendOptions` object, which is what I believe breaks the tests

**Comment by rakeshpai** [comment]
Ah. I got confused since I couldn't find my changes for the default values for options and the conversion to arrow functions. https://github.com/errorception/staticify/commit/ff47227c8f28c72c0842853c153b42a77de2e43a and https://github.com/errorception/staticify/commit/1a40f9d669f87cd6bb1dd0eae0e8d6ed8c9ced5a

I see defaultOptions being built manually from options in this code, and the arrow functions are moved back to being old function declarations. Any reason for this change? Or did my change just get lost somehow? (Sorry, I'm not super-familiar with git merging stuff.)

**Comment by XhmikosR** [comment]
The arrow functions are there. If you mean, your change to variable declarations instead of function declarations, I just reverted that part because, well, there's no need for it. We could change that later after we stabilize everything, if you still want to.

**Comment by rakeshpai** [comment]
Well, it's not a big deal, but I had moved to arrow functions and function assignment instead of function declaration, because function declaration needs the extra knowledge of hoisting rules, which is just another thing for people to know when reading the code. You're depending on the hoisting rules in this code too, where you are `module.export`ing the staticify function before defining it. I know why this works, but it's a quirk of JS that one has to know. This gets especially tricky when you do function declarations within other blocks, like say within conditionals. The hosting rules are poorly defined in the ES spec, which has led to different interpreters handling these differently. It doesn't matter here, since we're only talking about node, but I consider it a bad practice to rely on the hoisting rules of JS. Function assignment leads to more predictable code.

[Some more info here](http://adripofjavascript.com/blog/drips/variable-and-function-hoisting.html). [I've also blogged about it](http://blog.rakeshpai.me/2008/12/function-declaration-vs-function.html). (10 years ago!)

Also, with function assignment, you can use `const` or `let` which limits its scope, whereas function declarations are an implicit var, afaik. So, function assignment is a all-round better idea. In my code elsewhere, I usually have lint rules preventing function declarations all together because of these complications.

The options object is wrongly handled as well. There's no need to create the `defaultOptions` object. Just use the object defaults and rest/spread operators I had used. My code has the downside of needing node 8.x, but it much more succinct, and doesn't need the additional ceremony for setting defaults.

In addition, the sendOptions are being sent to `send` incorrectly. `send` doesn't accept an argument called `sendOptions`, so `sendOptions` is currently just being ignored.

Also, there's an imperative `for(;;)` loop in `buildVersionHash`, which is a code smell. It shouldn't be necessary, and the built in array methods should be preferred instead.

Sorry for critiquing your code. I know that you're just helping. Please don't take this as a personal attack. If you prefer, I can rectify the code again, so you can see what I mean, in case you are confused.

**Comment by XhmikosR** [comment]
It's your call, I don't have a problem with this myself.

Anyway, please review the PR; now it should be fine.

**Comment by XhmikosR** [comment]
So, things left:

1. Should we even set `maxAge` to zero if it's passed as an option, regardless if the asset has been hashed?
2. We should probably list our options in README.md, any help is welcome.

**Comment by XhmikosR** [comment]
@rakeshpai: `git fetch && git reset --hard` before you do any further changes please.

**Comment by rakeshpai** [comment]
Thanks for the tip git reset --hard. I knew I was doing something wrong. I was probably looking at some stale version all along. Probably makes my comments above irrelevant. 

Anyway, I've made the changes to the options object now, and my tests pass locally. I'll have a look at what's up with the CI systems.

**Comment by rakeshpai** [comment]
Sorry. I'm dumb. Failing test locally as well. Looking into it.

**Comment by XhmikosR** [comment]
@rakeshpai: please do as I say.

1. git fetch
2. git reset --hard
3. Then make any changes and commit

If you have conflicts, you are doing it wrong.

**Comment by XhmikosR** [comment]
You are not following what I say above...

**Comment by rakeshpai** [comment]
Sorry about the mixup. I'm clearly not very good with git.

I've now done the 'git fetch` and the `git reset --hard` as you said. I don't get any conflicts locally anymore. My last commit should be clean.

I've fixed the tests now. CI should only run on node 8.

**Comment by XhmikosR** [comment]
No, I reverted your last push.

You need to do it again.

1. git fetch
2. git reset --hard
3. Then redo your changes

Why do we need to use node.js 8? The branch as I have it works fine on >= 4.

**Comment by rakeshpai** [comment]
I don't understand. I've done what you've said multiple times now. I can see my changes, my local tests pass, and CI has now passed. 

What problem does 'git fetch && git reset --hard' solve? I can understand the solution better if I understand the problem.

**Comment by XhmikosR** [comment]
Because what you keep pushing, is merge commits. You should **not** have any if you did what I said at that order...

**Comment by rakeshpai** [comment]
I'm confused now. Firstly, I don't understand why I was getting the git issues. Could you please point me to some article that describes what was going wrong, why it's bad, and what the solution is, so that I can learn more?

Secondly, I thought you said that there's a failing test or something? Since the CI systems say it's all green, what's the issue?

**Comment by XhmikosR** [comment]
I fixed any issues this morning. See https://github.com/errorception/staticify/pull/13#issuecomment-353535849

Regarding your git issues, it's normal because I rebased the branch to clean it up. Hence the conflicts, unless you reset like I told you so.

So, if you want to push anything to this branch:

1. git fetch
2. git reset --hard
3. Do any changes again, if they are still needed
4. Commit and push

If you end up with merge commits/conflicts or you can't push, you just didn't follow the steps above.

**Comment by rakeshpai** [comment]
You're telling me the steps to resolve the issue, which is fine, but doesn't explain the problem. Could you point me to an article that explains what the problem is, and how these steps fix it, please?

Not only have I followed the steps you gave me multiple times, I've even deleted my checkout and cloned from scratch. So these issues shouldn't recur. But I have not understood what happened. The steps to resolve the issue doesn't help me understand the problem.

**Comment by XhmikosR** [comment]
I told you, it's due to the rebase.

**Comment by rakeshpai** [comment]
Overall, your changes are fine though. I'm not a fan of a separate `sendOptions` parameter to be passed in, but you could argue either way, and it's fine really.

I don't like the `defaultOptions` all over the code. I prefer to destructure the options object with default params as it comes in. That does restrict it to 8.0, so I'm not going to insist on the destructuring. Your code has broader support. Could we consider another name though? It isn't default options if it merges in the user's settings, is it?

In `buildVersionHash`, is the check with `defaultOptions.includeAll === true` correct? It looks like if includeAll is true, then ignore some directories, which seems incorrect. Also, could you relook that for loop? Maybe you want to use `Array.some` there?

The maxAge 0 is there for files without a version hash, because you don't want it to be cached for long. What do you suggest instead?

**Comment by XhmikosR** [comment]
In the last commit I added a function `setOptions` to handle options' setting.

I don't think we need destructing for such a small project.

For `maxAge`, if the user sets it, shouldn't we use that value even for unhashed assets? It seems a little inconsistent, that's all.

Only thing we need then is to document the options we have, make any changes to match your style and we should be ready to ship. Perhaps with a major version bump since the `sendOptions` are moved, although we could migrate them if you want.

>In buildVersionHash, is the check with defaultOptions.includeAll === true correct? It looks like if includeAll is true, then ignore some directories, which seems incorrect. Also, could you relook that for loop? Maybe you want to use Array.some there?

You are correct, totally missed it. It should be the opposite. I went with a simple `for` loop because then we can just return without more refactoring. But feel free to change the loop if it works with >=4.

**Comment by rakeshpai** [comment]
```js
if (opts.includeAll === false) {
    for (let i = 0, len = ignoredDirectories.length; i < len; i++) {
        if (directory.includes(ignoredDirectories[i])) {
            return;
        }
    }
}
```
can change to 
```js
if (!opts.includeAll && ignoredDirectories.some(d => directory.includes(d)) {
  return
}
```
This also does the early return you're probably going for, since `.some` doesn't iterate over the whole list if it doesn't have to.

You're right about maxAge. We only need to specify it if we're adding hashes. If not, we can use the user's maxAge, or let send use its default.

**Comment by XhmikosR** [comment]
Your example doesn't seem to be valid. Feel free to push another way as long as everything is green.

I'll try to update README.md later.

**Comment by rakeshpai** [comment]
I'm not sure what's going on with my git anymore. So, I'll not commit while you're working on this as well. That said, I tried the code and npm test runs with all tests passing. You said the example doesn't seem to be valid? What's not valid, in what way?

**Comment by XhmikosR** [comment]
```
> staticify@1.0.0 xo C:\Users\xmr\Desktop\staticify
> xo


  index.js:33:85
  ×  33:85  Parsing error: Unexpected token {
```

**Comment by rakeshpai** [comment]
Sorry, I had missed one closing paren.
```js
if (!opts.includeAll && ignoredDirectories.some(d => directory.includes(d))) {
    return;
}
```

**Comment by XhmikosR** [comment]
@rakeshpai: that works, so I switched to it.

Can you do one final review? I didn't change the maxAge, maybe we should do it in another PR.

**Comment by rakeshpai** [comment]
Looks good to me. Tests are much faster now - how did you do that?

Minor tweak: MAX_AGE can be defined in the outermost scope - doesn't need to be inside the staticify function.

Let's give this a new major version number.

**Comment by XhmikosR** [comment]
`includeAll` is false so traversing the folder is faster :)

**Pull request merged**
