### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
CI doesn't seem to fire up for the repo. We might need to contact GH Support.

**Comment by rakeshpai** [comment]
Could it be that the the yml needs to be in the repo (not just a PR) for it to work?

**Comment by XhmikosR** [comment]
It shouldn't matter, it should still fire up.

**Comment by rakeshpai** [comment]
The actions tab at the top makes it pretty clear that it's not configured yet though, which I why I think it might be worth just merging this to see what happens.

**Comment by XhmikosR** [comment]
No, it shouldn't be merged. The Actions should fire up in this PR.

**Comment by rakeshpai** [comment]
Ok. Contacted support. I'll update this thread when I hear back.

**Comment by XhmikosR** [comment]
@rakeshpai this could be because I'm not an org collaborator, I just have push rights to this repo and for security reasons Actions don't run in this case.

We can merge it and see how it goes.

**Comment by rakeshpai** [comment]
Looks like it did the trick!

**Comment by XhmikosR** [comment]
Perfect :)

I removed Travis from the repo.

**Comment by XhmikosR** [comment]
BTW can you check the repo hooks? It seems there's one hook left that's failing. If it's not used, better remove it.

**Comment by rakeshpai** [comment]
Deactivated the hook. No idea what that was doing there.

**Pull request merged**
